/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/models/human_teeth_alex_low.glb --keepmeshes --types 
Author: Alexander Antipov (https://sketchfab.com/Dessen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/human-teeth-c4c569f0e08948e2a572007a7a5726f2
Title: Human teeth
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Gums_GumsMaterial_0: THREE.Mesh
    Teeth_TeethMaterial_0: THREE.Mesh
  }
  materials: {
    GumsMaterial: THREE.MeshStandardMaterial
    TeethMaterial: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/human_teeth_alex_low.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Gums_GumsMaterial_0.geometry} material={materials.GumsMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0.geometry} material={materials.TeethMaterial} />
    </group>
  )
}

useGLTF.preload('/human_teeth_alex_low.glb')
