/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/models/human_teeth.glb --keepmeshes --types 
*/

import * as THREE from "three";
import React, { useMemo } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { extend, ThreeEvent } from "@react-three/fiber";
import { OrbitControls, Text } from "@react-three/drei";
import { MeshLineGeometry, MeshLineMaterial, raycast } from "meshline";
import { Elastic } from "../../types";

extend({ MeshLineGeometry, MeshLineMaterial });

// Fix for TypeScript errors with meshline components
declare global {
  namespace JSX {
    interface IntrinsicElements {
      meshLineGeometry: any;
      meshLineMaterial: any;
    }
  }
}

type GLTFResult = GLTF & {
  nodes: {
    Gums: THREE.Mesh;
    Tooth11: THREE.Mesh;
    Tooth12: THREE.Mesh;
    Tooth13: THREE.Mesh;
    Tooth14: THREE.Mesh;
    Tooth15: THREE.Mesh;
    Tooth16: THREE.Mesh;
    Tooth17: THREE.Mesh;
    Tooth21: THREE.Mesh;
    Tooth22: THREE.Mesh;
    Tooth23: THREE.Mesh;
    Tooth24: THREE.Mesh;
    Tooth25: THREE.Mesh;
    Tooth26: THREE.Mesh;
    Tooth27: THREE.Mesh;
    Tooth31: THREE.Mesh;
    Tooth32: THREE.Mesh;
    Tooth33: THREE.Mesh;
    Tooth34: THREE.Mesh;
    Tooth35: THREE.Mesh;
    Tooth36: THREE.Mesh;
    Tooth37: THREE.Mesh;
    Tooth41: THREE.Mesh;
    Tooth42: THREE.Mesh;
    Tooth43: THREE.Mesh;
    Tooth44: THREE.Mesh;
    Tooth45: THREE.Mesh;
    Tooth46: THREE.Mesh;
    Tooth47: THREE.Mesh;
  };
  materials: {
    Low_Teeth27: THREE.MeshStandardMaterial;
    Low_Teeth25: THREE.MeshStandardMaterial;
  };
  animations: any[];
};

interface TeethModel3DProps {
  onToothClick?: (toothNumber: number, event?: ThreeEvent<MouseEvent>) => void;
  elastics: Elastic[];
}

// Map of tooth numbers to their approximate 3D positions based on text positions
const toothPositions: { [key: number]: [number, number, number] } = {
  11: [-0.075, -1.23, 1.03],
  12: [-0.21, -1.23, 0.95],
  13: [-0.34, -1.23, 0.85],
  14: [-0.4, -1.24, 0.7],
  15: [-0.45, -1.25, 0.5],
  16: [-0.46, -1.26, 0.34],
  17: [-0.47, -1.26, 0.2],

  21: [0.075, -1.23, 1.03],
  22: [0.19, -1.23, 0.95],
  23: [0.27, -1.23, 0.86],
  24: [0.345, -1.24, 0.74],
  25: [0.39, -1.25, 0.59],
  26: [0.405, -1.26, 0.43],
  27: [0.43, -1.26, 0.29],

  31: [0.075, -1.4, 1.03],
  32: [0.19, -1.4, 0.95],
  33: [0.27, -1.4, 0.86],
  34: [0.345, -1.4, 0.74],
  35: [0.39, -1.4, 0.59],
  36: [0.405, -1.4, 0.43],
  37: [0.43, -1.4, 0.29],

  41: [-0.075, -1.4, 1.03],
  42: [-0.21, -1.4, 0.95],
  43: [-0.34, -1.4, 0.85],
  44: [-0.4, -1.4, 0.7],
  45: [-0.45, -1.4, 0.5],
  46: [-0.46, -1.4, 0.34],
  47: [-0.47, -1.4, 0.2],
};

// Offset for inside vs outside of teeth
const sideOffset: { [key: boolean]: [number, number, number] } = {
  true: [0, 0, 0.05], // outside
  false: [0, 0, -0.05], // inside
};

// Colors and thickness for different elastic types
const ELASTIC_TYPES = [
  { id: 0, name: "Rabbit", color: "#FF5555", thickness: 0.03 },
  { id: 1, name: "Chipmunk", color: "#5555CC", thickness: 0.04 },
  { id: 2, name: "Fox", color: "#44DD44", thickness: 0.05 },
];

export function TeethModel3D(props: TeethModel3DProps) {
  const { onToothClick, elastics = [] } = props;
  const { nodes, materials } = useGLTF(
    "assets/models/human_teeth.glb"
  ) as unknown as GLTFResult;

  const handleToothClick = (
    toothNumber: number,
    event: ThreeEvent<MouseEvent>
  ) => {
    if (!onToothClick) return;

    event.stopPropagation();
    return onToothClick(toothNumber, event);
  };

  // Generate elastic line data
  const elasticLines = useMemo(() => {
    return elastics
      .map((elastic) => {
        // Skip if not enough points
        if (elastic.teeth.length < 2) return null;

        // Get positions for each tooth in this elastic
        const points = elastic.teeth
          .map((point) => {
            const basePosition = toothPositions[point.tooth];
            if (!basePosition) return null;

            // Apply offset based on inside/outside
            const offset = sideOffset[point.outside];
            return [
              basePosition[0] + (offset?.[0] || 0),
              basePosition[1] + (offset?.[1] || 0),
              basePosition[2] + (offset?.[2] || 0),
            ] as [number, number, number];
          })
          .filter((pos) => pos !== null) as [number, number, number][];

        if (points.length < 2) return null;

        // Get the elastic type configuration
        const elasticTypeConfig =
          ELASTIC_TYPES.find((et) => et.id === elastic.type) ||
          ELASTIC_TYPES[0];

        return {
          points,
          color: elasticTypeConfig.color,
          thickness: elasticTypeConfig.thickness,
        };
      })
      .filter((line) => line !== null);
  }, [elastics]);

  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.359, -0.5]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Gums.geometry}
            material={materials.Low_Teeth27}
            onClick={(e) => handleToothClick(27, e)}
          />
          <mesh
            geometry={nodes.Tooth11.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(11, e)}
          />
          <mesh
            geometry={nodes.Tooth12.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(12, e)}
          />
          <mesh
            geometry={nodes.Tooth13.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(13, e)}
          />
          <mesh
            geometry={nodes.Tooth14.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(14, e)}
          />
          <mesh
            geometry={nodes.Tooth15.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(15, e)}
          />
          <mesh
            geometry={nodes.Tooth16.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(16, e)}
          />
          <mesh
            geometry={nodes.Tooth17.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(17, e)}
          />
          <mesh
            geometry={nodes.Tooth21.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(21, e)}
          />
          <mesh
            geometry={nodes.Tooth22.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(22, e)}
          />
          <mesh
            geometry={nodes.Tooth23.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(23, e)}
          />
          <mesh
            geometry={nodes.Tooth24.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(24, e)}
          />
          <mesh
            geometry={nodes.Tooth25.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(25, e)}
          />
          <mesh
            geometry={nodes.Tooth26.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(26, e)}
          />
          <mesh
            geometry={nodes.Tooth27.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(27, e)}
          />
          <mesh
            geometry={nodes.Tooth31.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(31, e)}
          />
          <mesh
            geometry={nodes.Tooth32.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(32, e)}
          />
          <mesh
            geometry={nodes.Tooth33.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(33, e)}
          />
          <mesh
            geometry={nodes.Tooth34.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(34, e)}
          />
          <mesh
            geometry={nodes.Tooth35.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(35, e)}
          />
          <mesh
            geometry={nodes.Tooth36.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(36, e)}
          />
          <mesh
            geometry={nodes.Tooth37.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(37, e)}
          />
          <mesh
            geometry={nodes.Tooth41.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(41, e)}
          />
          <mesh
            geometry={nodes.Tooth42.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(42, e)}
          />
          <mesh
            geometry={nodes.Tooth43.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(43, e)}
          />
          <mesh
            geometry={nodes.Tooth44.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(44, e)}
          />
          <mesh
            geometry={nodes.Tooth45.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(45, e)}
          />
          <mesh
            geometry={nodes.Tooth46.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(46, e)}
          />
          <mesh
            geometry={nodes.Tooth47.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(47, e)}
          />
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[-0.075, -1.23, 1.03]}
            rotation={[0, -0.2, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            11
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[-0.21, -1.23, 0.95]}
            rotation={[0, -0.65, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            12
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[-0.3, -1.23, 0.85]}
            rotation={[0, -0.9, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            13
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[-0.38, -1.24, 0.73]}
            rotation={[0, -1.1, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            14
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[-0.41, -1.25, 0.6]}
            rotation={[0, -1.4, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            15
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[-0.43, -1.26, 0.43]}
            rotation={[0, -1.35, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            16
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[-0.45, -1.26, 0.29]}
            rotation={[0, -1.4, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            17
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[0.075, -1.23, 1.03]}
            rotation={[0, 0.2, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            21
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[0.19, -1.23, 0.95]}
            rotation={[0, 0.65, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            22
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[0.27, -1.23, 0.86]}
            rotation={[0, 0.9, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            23
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[0.345, -1.24, 0.74]}
            rotation={[0, 1.1, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            24
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[0.39, -1.25, 0.59]}
            rotation={[0, 1.4, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            25
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[0.405, -1.26, 0.43]}
            rotation={[0, 1.35, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            26
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[0.43, -1.26, 0.29]}
            rotation={[0, 1.4, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            27
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[0.075, -1.44, 0.99]}
            rotation={[0, 0.2, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            31
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[0.19, -1.44, 0.9]}
            rotation={[0, 0.65, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            32
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[0.27, -1.44, 0.81]}
            rotation={[0, 0.9, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            33
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[0.34, -1.44, 0.72]}
            rotation={[0, 1.1, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            34
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[0.36, -1.43, 0.58]}
            rotation={[0, 1.4, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            35
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[0.405, -1.42, 0.43]}
            rotation={[0, 1.35, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            36
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[0.43, -1.4, 0.29]}
            rotation={[0, 1.4, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            37
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[-0.075, -1.44, 0.99]}
            rotation={[0, -0.2, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            41
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[-0.21, -1.44, 0.9]}
            rotation={[0, -0.65, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            42
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[-0.28, -1.44, 0.83]}
            rotation={[0, -0.9, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            43
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[-0.35, -1.44, 0.71]}
            rotation={[0, -1.1, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            44
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[-0.38, -1.43, 0.58]}
            rotation={[0, -1.4, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            45
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[-0.4, -1.42, 0.43]}
            rotation={[0, -1.35, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            46
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[-0.44, -1.4, 0.27]}
            rotation={[0, -1.4, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            47
          </Text>

          {/* Render elastic lines based on the elastics prop */}
          {elasticLines.map(
            (elastic, idx) =>
              elastic && (
                <mesh key={`elastic-${idx}`} raycast={raycast}>
                  <meshLineGeometry points={elastic.points} />
                  <meshLineMaterial
                    lineWidth={elastic.thickness}
                    color={elastic.color}
                    transparent
                    depthTest={false}
                  />
                </mesh>
              )
          )}

          <OrbitControls enableZoom={false} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("assets/models/human_teeth.glb");
