/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/models/human_teeth.glb --keepmeshes --types 
*/

import * as THREE from "three";
import { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { extend, ThreeEvent } from "@react-three/fiber";
import { OrbitControls, Text } from "@react-three/drei";
import { MeshLineGeometry, MeshLineMaterial, raycast } from "meshline";
import { ElasticPoint } from "../../types";

extend({ MeshLineGeometry, MeshLineMaterial });

type GLTFResult = GLTF & {
  nodes: {
    Gums: THREE.Mesh;
    Tooth11: THREE.Mesh;
    Tooth12: THREE.Mesh;
    Tooth13: THREE.Mesh;
    Tooth14: THREE.Mesh;
    Tooth15: THREE.Mesh;
    Tooth16: THREE.Mesh;
    Tooth17: THREE.Mesh;
    Tooth21: THREE.Mesh;
    Tooth22: THREE.Mesh;
    Tooth23: THREE.Mesh;
    Tooth24: THREE.Mesh;
    Tooth25: THREE.Mesh;
    Tooth26: THREE.Mesh;
    Tooth27: THREE.Mesh;
    Tooth31: THREE.Mesh;
    Tooth32: THREE.Mesh;
    Tooth33: THREE.Mesh;
    Tooth34: THREE.Mesh;
    Tooth35: THREE.Mesh;
    Tooth36: THREE.Mesh;
    Tooth37: THREE.Mesh;
    Tooth41: THREE.Mesh;
    Tooth42: THREE.Mesh;
    Tooth43: THREE.Mesh;
    Tooth44: THREE.Mesh;
    Tooth45: THREE.Mesh;
    Tooth46: THREE.Mesh;
    Tooth47: THREE.Mesh;
  };
  materials: {
    Low_Teeth27: THREE.MeshStandardMaterial;
    Low_Teeth25: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type TeethModel3DProps = JSX.IntrinsicElements["group"] & {
  onToothClick?: (toothNumber: number, event: ThreeEvent<MouseEvent>) => void;
  currentElastic: ElasticPoint[];
};

export function TeethModel3D(props: TeethModel3DProps) {
  const { onToothClick } = props;
  const { nodes, materials } = useGLTF(
    "assets/models/human_teeth.glb"
  ) as unknown as GLTFResult;

  const handleToothClick = (
    toothNumber: number,
    event: ThreeEvent<MouseEvent>
  ) => {
    if (!onToothClick) return;

    event.stopPropagation();
    return onToothClick(toothNumber, event);
  };

  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.359, -0.5]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Gums.geometry}
            material={materials.Low_Teeth27}
            onClick={(e) => handleToothClick(27, e)}
          />
          <mesh
            geometry={nodes.Tooth11.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(11, e)}
          />
          <mesh
            geometry={nodes.Tooth12.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(12, e)}
          />
          <mesh
            geometry={nodes.Tooth13.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(13, e)}
          />
          <mesh
            geometry={nodes.Tooth14.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(14, e)}
          />
          <mesh
            geometry={nodes.Tooth15.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(15, e)}
          />
          <mesh
            geometry={nodes.Tooth16.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(16, e)}
          />
          <mesh
            geometry={nodes.Tooth17.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(17, e)}
          />
          <mesh
            geometry={nodes.Tooth21.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(21, e)}
          />
          <mesh
            geometry={nodes.Tooth22.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(22, e)}
          />
          <mesh
            geometry={nodes.Tooth23.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(23, e)}
          />
          <mesh
            geometry={nodes.Tooth24.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(24, e)}
          />
          <mesh
            geometry={nodes.Tooth25.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(25, e)}
          />
          <mesh
            geometry={nodes.Tooth26.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(26, e)}
          />
          <mesh
            geometry={nodes.Tooth27.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(27, e)}
          />
          <mesh
            geometry={nodes.Tooth31.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(31, e)}
          />
          <mesh
            geometry={nodes.Tooth32.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(32, e)}
          />
          <mesh
            geometry={nodes.Tooth33.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(33, e)}
          />
          <mesh
            geometry={nodes.Tooth34.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(34, e)}
          />
          <mesh
            geometry={nodes.Tooth35.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(35, e)}
          />
          <mesh
            geometry={nodes.Tooth36.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(36, e)}
          />
          <mesh
            geometry={nodes.Tooth37.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(37, e)}
          />
          <mesh
            geometry={nodes.Tooth41.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(41, e)}
          />
          <mesh
            geometry={nodes.Tooth42.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(42, e)}
          />
          <mesh
            geometry={nodes.Tooth43.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(43, e)}
          />
          <mesh
            geometry={nodes.Tooth44.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(44, e)}
          />
          <mesh
            geometry={nodes.Tooth45.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(45, e)}
          />
          <mesh
            geometry={nodes.Tooth46.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(46, e)}
          />
          <mesh
            geometry={nodes.Tooth47.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => handleToothClick(47, e)}
          />
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[-0.075, -1.23, 1.03]}
            rotation={[0, -0.2, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            11
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[-0.21, -1.23, 0.95]}
            rotation={[0, -0.65, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            12
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[0.075, -1.23, 1.03]}
            rotation={[0, 0.2, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            21
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[0.19, -1.23, 0.95]}
            rotation={[0, 0.65, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            22
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[0.27, -1.23, 0.86]}
            rotation={[0, 0.9, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            23
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[0.345, -1.24, 0.74]}
            rotation={[0, 1.1, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            24
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[0.39, -1.25, 0.59]}
            rotation={[0, 1.4, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            25
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[0.405, -1.26, 0.43]}
            rotation={[0, 1.35, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            26
          </Text>
          <Text
            fontSize={0.25}
            scale={[0.25, 0.25, 1]}
            position={[0.43, -1.26, 0.29]}
            rotation={[0, 1.4, 0]}
            color="#333333"
            anchorX="center"
            anchorY="middle"
          >
            27
          </Text>

          <mesh raycast={raycast}>
            <meshLineGeometry
              points={[
                [-0.2, -1.2, 1],
                [-0.3, -1.4, 0.8],
              ]}
            />
            {/* If you're rendering transparent lines or using a texture with alpha map, you should set depthTest to false, transparent to true and blending to an appropriate blending mode, or use alphaTest. */}
            <meshLineMaterial
              lineWidth={0.05}
              color="#dd0000"
              transparent
              depthTest={false}
            />
          </mesh>

          <OrbitControls />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("assets/models/human_teeth.glb");
