/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/models/human_teeth.glb 
Author: sassimedamine (https://sketchfab.com/sassimedamine)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/human-teeth-d3daee92c71b40ab86ac528c5f2f560a
Title: Human teeth
*/

import { useGLTF } from '@react-three/drei'
import { JSX } from 'react'

type ModelProps = JSX.IntrinsicElements['div'] & {
  onToothClick?: (toothName: string) => void
}

export function TeethModel3D(props: ModelProps) {
  const { nodes, materials } = useGLTF('/assets/models/human_teeth.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Low_Teeth27_Low_Teeth27_0.geometry} material={materials.Low_Teeth27} />
      <mesh geometry={nodes.Low_Teeth25_Low_Teeth25_0.geometry} material={materials.Low_Teeth25} />
    </group>
  )
}

useGLTF.preload('/assets/models/human_teeth.glb')
