/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/models/human_teeth.glb --keepmeshes --types 
*/

import * as THREE from "three";
import { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { ThreeEvent } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    Gums: THREE.Mesh;
    Tooth11: THREE.Mesh;
    Tooth12: THREE.Mesh;
    Tooth13: THREE.Mesh;
    Tooth14: THREE.Mesh;
    Tooth15: THREE.Mesh;
    Tooth16: THREE.Mesh;
    Tooth17: THREE.Mesh;
    Tooth21: THREE.Mesh;
    Tooth22: THREE.Mesh;
    Tooth23: THREE.Mesh;
    Tooth24: THREE.Mesh;
    Tooth25: THREE.Mesh;
    Tooth26: THREE.Mesh;
    Tooth27: THREE.Mesh;
    Tooth31: THREE.Mesh;
    Tooth32: THREE.Mesh;
    Tooth33: THREE.Mesh;
    Tooth34: THREE.Mesh;
    Tooth35: THREE.Mesh;
    Tooth36: THREE.Mesh;
    Tooth37: THREE.Mesh;
    Tooth41: THREE.Mesh;
    Tooth42: THREE.Mesh;
    Tooth43: THREE.Mesh;
    Tooth44: THREE.Mesh;
    Tooth45: THREE.Mesh;
    Tooth46: THREE.Mesh;
    Tooth47: THREE.Mesh;
  };
  materials: {
    Low_Teeth27: THREE.MeshStandardMaterial;
    Low_Teeth25: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type TeethModel3DProps = JSX.IntrinsicElements["group"] & {
  onToothClick?: (toothNumber: number, event: ThreeEvent<MouseEvent>) => void;
};

export function TeethModel3D(props: TeethModel3DProps) {
  const { onToothClick } = props;
  const { nodes, materials } = useGLTF(
    "/assets/models/human_teeth.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.359, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Gums.geometry}
            material={materials.Low_Teeth27}
            onClick={(e) => onToothClick?.(27, e)}
          />
          <mesh
            geometry={nodes.Tooth11.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => onToothClick?.(11, e)}
          />
          <mesh
            geometry={nodes.Tooth12.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => onToothClick?.(12, e)}
          />
          <mesh
            geometry={nodes.Tooth13.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => onToothClick?.(13, e)}
          />
          <mesh
            geometry={nodes.Tooth14.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => onToothClick?.(14, e)}
          />
          <mesh
            geometry={nodes.Tooth15.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => onToothClick?.(15, e)}
          />
          <mesh
            geometry={nodes.Tooth16.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => onToothClick?.(16, e)}
          />
          <mesh
            geometry={nodes.Tooth17.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => onToothClick?.(17, e)}
          />
          <mesh
            geometry={nodes.Tooth21.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => onToothClick?.(21, e)}
          />
          <mesh
            geometry={nodes.Tooth22.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => onToothClick?.(22, e)}
          />
          <mesh
            geometry={nodes.Tooth23.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => onToothClick?.(23, e)}
          />
          <mesh
            geometry={nodes.Tooth24.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => onToothClick?.(24, e)}
          />
          <mesh
            geometry={nodes.Tooth25.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => onToothClick?.(25, e)}
          />
          <mesh
            geometry={nodes.Tooth26.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => onToothClick?.(26, e)}
          />
          <mesh
            geometry={nodes.Tooth27.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => onToothClick?.(27, e)}
          />
          <mesh
            geometry={nodes.Tooth31.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => onToothClick?.(31, e)}
          />
          <mesh
            geometry={nodes.Tooth32.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => onToothClick?.(32, e)}
          />
          <mesh
            geometry={nodes.Tooth33.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => onToothClick?.(33, e)}
          />
          <mesh
            geometry={nodes.Tooth34.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => onToothClick?.(34, e)}
          />
          <mesh
            geometry={nodes.Tooth35.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => onToothClick?.(35, e)}
          />
          <mesh
            geometry={nodes.Tooth36.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => onToothClick?.(36, e)}
          />
          <mesh
            geometry={nodes.Tooth37.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => onToothClick?.(37, e)}
          />
          <mesh
            geometry={nodes.Tooth41.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => onToothClick?.(41, e)}
          />
          <mesh
            geometry={nodes.Tooth42.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => onToothClick?.(42, e)}
          />
          <mesh
            geometry={nodes.Tooth43.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => onToothClick?.(43, e)}
          />
          <mesh
            geometry={nodes.Tooth44.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => onToothClick?.(44, e)}
          />
          <mesh
            geometry={nodes.Tooth45.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => onToothClick?.(45, e)}
          />
          <mesh
            geometry={nodes.Tooth46.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => onToothClick?.(46, e)}
          />
          <mesh
            geometry={nodes.Tooth47.geometry}
            material={materials.Low_Teeth25}
            onClick={(e) => onToothClick?.(47, e)}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/assets/models/human_teeth.glb");
