/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/models/human_teeth_dewa_low.glb --types 
Author: dewa (https://sketchfab.com/dewa)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/teeth-3a0fb31b9d864b27a0846aca8579461c
Title: Teeth
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_3: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
  };
  materials: {
    Gums: THREE.MeshStandardMaterial;
    Teeth: THREE.MeshStandardMaterial;
    Tongue: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function TeethModel3DDewa(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/assets/models/human_teeth_dewa_low.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={4.135}>
        <group position={[-0.262, -0.314, 4.671]}>
          <mesh geometry={nodes.Object_3.geometry} material={materials.Gums} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.Gums} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.Gums} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.Teeth} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.Teeth} />
          <mesh
            geometry={nodes.Object_8.geometry}
            material={materials.Tongue}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/assets/models/human_teeth_dewa_low.glb");
