export const FEATURES = {
  DISABLE_TEETH: false,
  HIGHLIGHT_SPECIAL_TEETH: false,
  MIRROR_VIEW: true,
  TOOTH_ICONS: true,
  ALLOW_MULTIPLE_ELASTICS_PER_TOOTH: false,
  TIME_BASED_ELASTICS: true,
} as const;
